### ISSUE TITLE
Delete nested resources when deployment is deleted

### ISSUE THREAD

**Issue by schnie** [astronomerio/houston-api#30]
Currently when a user issues a delete on an airflow deployment, we only delete the records in the houston database. We need to cascade deletes down to:

- [x] Kubernetes release
- [ ] The deployment's airflow metadata database
- [x] The helm chart
- [x] The `PersistentVolumes` that get left around

Let's try and get this into 0.3 since it solves some potential issues people will run into immediately.

[TE] Recent work on this:

- [x] ramp up on commander
- [x] ramp up on minimal houston
- [x] review existing delete deployment PR code changes
- [x] start changing code
- [x] ship + merge code

**Comment by tedmiston** [comment]
Some updates over the past 24 hours:

- CJ gave me a crash course in Commander and Houston and I've ramped up on a lot of this yesterday and today.
- I have the execution path traced out from Commander client to Commander server and I think the relevant components figured out, and started changing the code.
- @cwurtz and I are going to pair on Monday morning on what's left since these codebases are new to me and he has a lot of experience with them if we're considering adding this to the initial release of 0.3.  Our goal is to ship a working version on Monday.

**Comment by tedmiston** [comment]
We're pretty much done here.  Commander changes are now merged.  We can call this issue closed with CJ's merge of Houston tonight.

**Comment by schnie** [comment]
This didn't work during testing. Seems like we have some things to clean up still.

**Comment by tedmiston** [comment]
Can we call this closed now @schnie?

**Comment by schnie** [comment]
Yep
